// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqkgX9KsM5J19UAkjVJJL4kOFyhKJUeJ4',
    appId: '1:729321326933:android:d14af93517a3f10bdd87dc',
    messagingSenderId: '729321326933',
    projectId: 'management-apartment',
    storageBucket: 'management-apartment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlKb5UsOQysL3YNYFYqeNldP6jjvDn7Is',
    appId: '1:729321326933:ios:96e70b0ed2e66ad9dd87dc',
    messagingSenderId: '729321326933',
    projectId: 'management-apartment',
    storageBucket: 'management-apartment.firebasestorage.app',
    iosBundleId: 'com.example.apartmentManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlKb5UsOQysL3YNYFYqeNldP6jjvDn7Is',
    appId: '1:729321326933:ios:96e70b0ed2e66ad9dd87dc',
    messagingSenderId: '729321326933',
    projectId: 'management-apartment',
    storageBucket: 'management-apartment.firebasestorage.app',
    iosBundleId: 'com.example.apartmentManagement',
  );
}
