// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdwR4_nwCrPvhiCBRDk5Q9YRIQaemliVw',
    appId: '1:1038744483020:android:0ded9245ad6acfd0083e69',
    messagingSenderId: '1038744483020',
    projectId: 'apartment-management-9ab83',
    storageBucket: 'apartment-management-9ab83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqSOljfFhWIgvg0SlkPSXVBzqKB46aduU',
    appId: '1:1038744483020:ios:ea809abd5a88ba9b083e69',
    messagingSenderId: '1038744483020',
    projectId: 'apartment-management-9ab83',
    storageBucket: 'apartment-management-9ab83.appspot.com',
    iosBundleId: 'com.example.apartmentManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqSOljfFhWIgvg0SlkPSXVBzqKB46aduU',
    appId: '1:1038744483020:ios:ea809abd5a88ba9b083e69',
    messagingSenderId: '1038744483020',
    projectId: 'apartment-management-9ab83',
    storageBucket: 'apartment-management-9ab83.appspot.com',
    iosBundleId: 'com.example.apartmentManagement',
  );
}
